計算を行う処理を追加
is-club-SmartAppBootCamp/ooutputCalculation pull request #2
Opened 2019-11-04 16:28 UTC by novatoka

# 計算を行うクラス、処理の追加
- 「計算結果」ボタン押下時の処理を追加。
- 計算をCalculatorクラスの作成。

___
# 確認方法
- コードを実行する。
- テキスト入力欄に値を入力、四則演算子を選択する。
- 「計算結果」ボタンを押下する。
- 「計算結果表示」に「入力した値」と「選択した四則演算子」、「計算結果」が表示されることを確認する。

2019-11-05 13:39 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +     * @param num1Str 値１
コメントがウソを付いている
num1Strなんて引数ないですね

2019-11-05 13:40 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +     * @param num1Str 値１
ここは変数名書くところっす

2019-11-05 13:41 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(x: String, y: String, A: String): Int {
xやyじゃ何を表す変数なのか分からないのでリネームしてください。
あとなぜAだけ大文字？

2019-11-05 13:43 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        if(A == "+"){
if else で複数の条件分岐をする場合、 `when` が使えます。

[FYI]
https://qiita.com/AAkira/items/3d5b694d488fe029d7b9

2019-11-05 13:43 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        /*
不要なコメントは消しましょうね～

2019-11-05 13:51 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/MainActivity.kt
> +        val num1Str = (findViewById<EditText>(R.id.num1)).text.toString()
ここ、どうやらこんなまどろっこしい取り方しなくてもいいみたいです
[この行](https://github.com/is-club-SmartAppBootCamp/ooutputCalculation/pull/2/files#diff-3c7a4a4ad943011418cf343f13cbd609R28)みたいに直接参照していいみたいね
https://qiita.com/sekitaka_1214/items/7d1156e56c2a670ea649

2019-11-05 17:52 UTC, inokinn requested changes
指摘内容の反映おねがいします～
というわけで Request changes にしときます

2019-11-07 15:13 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +     * @param num1Str 値１
変数名の修正に合わせて、修正しました。

2019-11-07 15:17 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(x: String, y: String, A: String): Int {
変数名を修正しました。

2019-11-07 15:18 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        if(A == "+"){
if else文を、when文に変更しました。

2019-11-07 15:19 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        /*
コメントの見直しを行い、不要なものは削除しました。

2019-11-07 15:19 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/MainActivity.kt
> +        val num1Str = (findViewById<EditText>(R.id.num1)).text.toString()
ID名で取得できるように修正しました。

2019-11-07 15:24 UTC, novatoka commented
指摘事項の修正を行いました。
再度確認をお願い致します。

2019-11-07 19:43 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(inp01: String, inp02: String, inpOper: String): Int {
変数名には変な略語を使ってはいけません。

`inp` が `input` の略だとは少し考えないと分からないし
`インプレッション` のスペルミスかな？って思っちゃった。
何より、たった2文字を略す理由が無い。

あと、 `01` って命名してるけど、2桁にはなり得ないので `0` いらないです。

2019-11-07 19:44 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(inp01: String, inp02: String, inpOper: String): Int {
`inpOper` も変数名から内容を推察できません

2019-11-07 19:45 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/MainActivity.kt
> +        //入力値の計算結果を取得
コメントするとき、 `//` と `コメント` の間にスペースを入れるか入れないか統一してください。
（入れたほうが行儀は良いです）

2019-11-07 19:47 UTC, inokinn commented on app/build.gradle
> +//画面の部品をID名で取得するため追加
'kotlin-android-extensions' の役割ってこれだけじゃない筈なので、このコメントは無い方がいいかもね

2019-11-07 19:48 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        val num1 = Integer.parseInt(inp01)
`num` と `inp` で命名が統一されてないので、関連性がわかりにくいですね

2019-11-08 03:47 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(inp01: String, inp02: String, inpOper: String): Int {
ちなみに `num` だって `number` の略じゃん！って思うかもしれないけど
`num` は割と一般的な略称です。
`info` のことをわざわざ `information` って言ったりしないのと一緒かな

2019-11-09 03:03 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +    fun execCalculation(inp01: String, inp02: String, inpOper: String): Int {
再度変数名を修正しました。

2019-11-09 03:04 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/MainActivity.kt
> +        //入力値の計算結果を取得
コメントの頭にスペースを入れました。

2019-11-09 03:17 UTC, novatoka commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        val num1 = Integer.parseInt(inp01)
関連するような名称にしましたが、あってますかね。。。

2019-11-09 03:18 UTC, novatoka commented
各箇所、再修正しました。

2019-11-09 03:18 UTC, novatoka commented on app/build.gradle
> +//画面の部品をID名で取得するため追加
コメントの削除をしました。

2019-11-09 07:14 UTC, inokinn approved these changes
LGTM です！
マージしちゃってください！
したら、準備は整ったのでテストコードを書いていきたいんですが
これ通話で説明しないとむずいな…

2019-11-09 07:15 UTC, inokinn commented on app/src/main/java/com/example/outputcalculation/Calculator.kt
> +        val num1 = Integer.parseInt(inp01)
おっけーです！

2019-11-10 04:28 UTC, merged